version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "==> Installing dependencies..."
      - pip install --upgrade pip
      - pip install --no-cache-dir awscli sagemaker==2.224.0 scikit-learn==1.2.2 boto3 pandas
      # - pip install snowflake-connector-python
      # - pip install -r requirements.txt

  build:
    commands:
      # - echo "Checking if data exists in S3..."

      #     - |
      #       if aws s3 ls s3://${S3_BUCKET}/${INPUT_DATA_KEY:-data/data.csv}; then
      #         echo "==> Data already exists in S3. Skipping upload."
      #       else
      #         echo "==> Data not found in S3."
              
      #         if [ -f "data.csv" ]; then
      #           echo "==> Uploading local data.csv to S3..."
      #           aws s3 cp data.csv s3://${S3_BUCKET}/${INPUT_DATA_KEY:-data/data.csv}
      #           echo "==> Upload complete."
      #         else
      #           echo "❌ ERROR: data.csv not found locally or in S3"
      #           exit 1
      #         fi
      #       fi

      - echo "Starting SageMaker pipeline..."
      - python pipeline.py

  post_build:
    commands:
      - echo "==> Build complete ✓"

artifacts:
  files:
    - "**/*"
  name: sagemaker-pipeline-artifact