version: 0.2

# env:
#   variables:
#     PIPELINE_NAME: "MyMLPipeline"
#     #INPUT_DATA_KEY: "blend-sagemaker-demo/data/data.csv"
#     ACCURACY_THRESHOLD: "0.80"
#     MODEL_APPROVAL_STATUS: "PendingManualApproval"

phases:

  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "==> Installing dependencies..."
      - pip install --upgrade pip
      - pip install --no-cache-dir awscli sagemaker==2.224.0 scikit-learn==1.2.2 boto3 pandas

  # pre_build:
  #   commands:
  #     - echo "==> Validating environment..."

  #     - '[ -z "$SAGEMAKER_ROLE_ARN" ] && echo "ERROR: SAGEMAKER_ROLE_ARN is not set" && exit 1 || true'
  #     - '[ -z "$S3_BUCKET" ] && echo "ERROR: S3_BUCKET is not set" && exit 1 || true'

  #     - echo "Pipeline name  : $PIPELINE_NAME"
  #     - echo "S3 bucket      : $S3_BUCKET"
  #     - echo "Region         : $AWS_DEFAULT_REGION"

  build:
    commands:
      - echo "Starting SageMaker pipeline..."
      - python pipeline.py

  post_build:
    commands:
      - echo "==> Build complete ✓"

artifacts:
  files:
    - "**/*"
  name: sagemaker-pipeline-artifact